/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import control.Control;
import java.awt.Image;
import objetosNegocio.*;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.DataOutputStream;
import java.net.Socket;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DlgCorreo extends javax.swing.JDialog {
    private Correo correo;
    private StringBuffer respuesta;
    private int operacion;

    /**
     * Creates new form DlgCorreo
     */
    public DlgCorreo(java.awt.Frame parent, String title, boolean modal, Correo correo, int operacion, StringBuffer respuesta) {
        super(parent, title, modal);
        this.correo = correo;
        this.respuesta = respuesta;
        this.operacion = operacion;
        initComponents();
        
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/etc/mlogo.png"));
        setIconImage(iconoPropio);
        
        if(operacion == ConstantesGUI.AGREGAR)botonEnviar.setText("");
        else if(operacion == ConstantesGUI.DESPLEGAR) {       
            botonCancelar.setIcon(new ImageIcon(getClass().getResource("/recursos/botones/aceptar.png")));
            botonEnviar.setEnabled(false);
            botonEnviar.setVisible(false);
            botonRestaurar.setIcon(new ImageIcon(getClass().getResource("/recursos/botones/agregarC.png")));
        }
        
        
        if((operacion == ConstantesGUI.DESPLEGAR)) { 
            campoIpDestinatario.setText(correo.getRemitente().getIp());    
            campoIpDestinatario.setEditable(false);
            campoCorreo.setText(correo.getRemitente().getDireccionCorreo());      
            campoCorreo.setEditable(false);
            campoAsunto.setText(correo.getAsunto());
            campoAsunto.setEditable(false);
            areaMensaje.setText(correo.getMensaje());
            areaMensaje.setEditable(false);
        }
        else if(operacion == ConstantesGUI.ACTUALIZAR){
            campoIpDestinatario.setText(correo.getDestinatario().getIp()); 
            campoIpDestinatario.setEditable(false);
            campoCorreo.setText(correo.getDestinatario().getDireccionCorreo());      
            campoCorreo.setEditable(false);
        }

        respuesta.append(ConstantesGUI.CANCELAR);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMensaje = new javax.swing.JTextArea();
        campoIpDestinatario = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        campoAsunto = new javax.swing.JTextField();
        botonRestaurar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonEnviar = new javax.swing.JButton();
        separador = new javax.swing.JLabel();
        separador2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IP del Destinatario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mensaje:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 33));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Asunto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 33));

        areaMensaje.setColumns(20);
        areaMensaje.setRows(5);
        jScrollPane1.setViewportView(areaMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 504, 264));

        campoIpDestinatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIpDestinatarioKeyTyped(evt);
            }
        });
        getContentPane().add(campoIpDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, -1));

        campoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(campoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 260, -1));
        getContentPane().add(campoAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 500, -1));

        botonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botones/restaurar.png"))); // NOI18N
        botonRestaurar.setBorderPainted(false);
        botonRestaurar.setContentAreaFilled(false);
        botonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaurarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botones/cancelar.png"))); // NOI18N
        botonCancelar.setBorderPainted(false);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        botonEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botones/enviar.png"))); // NOI18N
        botonEnviar.setBorderPainted(false);
        botonEnviar.setContentAreaFilled(false);
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));
        getContentPane().add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 30, 30));
        getContentPane().add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 30, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondos/fondo3.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        int posError=0;
        StringBuffer msjError = new StringBuffer();
        String ipDestinatario = campoIpDestinatario.getText();
        String correoUsuario = campoCorreo.getText();
        String asunto = campoAsunto.getText();
        String mensaje = areaMensaje.getText();
        
        String patronIp = "\\d{1,3}\\.\\d{1,3}.\\d{1,3}.\\d{1,3}";
        Pattern p = Pattern.compile(patronIp);
        Matcher matcherIp = p.matcher(campoIpDestinatario.getText());
        
        String patronCorreo = "\\w+@[a-z]+\\.[a-z]{1,4}";
        Pattern p2 = Pattern.compile(patronCorreo);
        Matcher matcherCorreo = p2.matcher(campoCorreo.getText());
        
        
         //Si hay IP y el formato está bien
        if (campoIpDestinatario.getText().isEmpty()){
                msjError.append("Falta la dirección IP\n");
                posError = 1;
            } else if (!matcherIp.matches()){
                msjError.append("Introduzca una dirección IP válida\n");
                posError = 1;
            }
        
        //Si hay correo y el formato está bien
            if(campoCorreo.getText().isEmpty()){
                msjError.append("El correo está vacio \n");
                if(posError==0){
                    posError=2;
                }
            }else if(!matcherCorreo.matches()){
                msjError.append("Introduzca una dirección de correo electrónico válida \n");
                if(posError==0){
                    posError=2;
                }
            }
            
            //Si hubo al menos un error despliega sus mensajes
            if(posError>0){
                JOptionPane.showMessageDialog(this, msjError,"Error",JOptionPane.ERROR_MESSAGE);
                //Haz que el campo de texto con el primer error obtenga el foco
                switch(posError){
                    case 1:
                        campoIpDestinatario.requestFocus();
                        break;
                    case 2:
                        campoCorreo.requestFocus();
                        break;
                }
                return;
            }
 
        Usuario destinatario = new Usuario("juanZZZ",correoUsuario,ipDestinatario);    
        correo.setDestinatario(destinatario);
        correo.setAsunto(asunto);
        correo.setMensaje(mensaje);

        respuesta.delete(0, respuesta.length());
        respuesta.append(ConstantesGUI.AGREGAR);
        dispose();
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void botonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaurarActionPerformed
       if(operacion == ConstantesGUI.AGREGAR){
        campoIpDestinatario.setText("");
        campoCorreo.setText("");
        campoAsunto.setText("");
        areaMensaje.setText("");
       }
       if(operacion==ConstantesGUI.ACTUALIZAR){
        campoAsunto.setText("");
        areaMensaje.setText("");
       }
        if(operacion == ConstantesGUI.DESPLEGAR){
            respuesta.delete(0, respuesta.length());
            respuesta.append(ConstantesGUI.AÑADIR_C);
            dispose();
        }
    }//GEN-LAST:event_botonRestaurarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoIpDestinatarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIpDestinatarioKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !(c == KeyEvent.VK_PERIOD)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }       
    }//GEN-LAST:event_campoIpDestinatarioKeyTyped

    private void campoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCorreoKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_campoCorreoKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensaje;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JButton botonRestaurar;
    private javax.swing.JTextField campoAsunto;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoIpDestinatario;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel separador;
    private javax.swing.JLabel separador2;
    // End of variables declaration//GEN-END:variables
}
