/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objetosNegocio.Usuario;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {
    private String rLogin = "Archivo/login.dat";
    private Usuario login = null;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/etc/mlogo.png"));
        setIconImage(iconoPropio);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        campoTextoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTextoCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        metaImagen = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetaMail");
        setBackground(new java.awt.Color(99, 176, 230));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("MetaMail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 140, 50));

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botones/aceptar.png"))); // NOI18N
        botonAceptar.setBorder(null);
        botonAceptar.setBorderPainted(false);
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, 40));

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/botones/cancelar.png"))); // NOI18N
        botonCancelar.setBorder(null);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 130, 40));

        campoTextoUsuario.setBackground(new java.awt.Color(0, 102, 204));
        campoTextoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        campoTextoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        campoTextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoUsuarioActionPerformed(evt);
            }
        });
        campoTextoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(campoTextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        campoTextoCorreo.setBackground(new java.awt.Color(0, 102, 204));
        campoTextoCorreo.setForeground(new java.awt.Color(255, 255, 255));
        campoTextoCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        campoTextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCorreoActionPerformed(evt);
            }
        });
        campoTextoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTextoCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(campoTextoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 201, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        metaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/etc/mlogo1.png"))); // NOI18N
        getContentPane().add(metaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 228, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondos/fondo2.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String ipUser ="";
        try(final DatagramSocket socket = new DatagramSocket()){
            socket.connect(InetAddress.getByName("8.8.8.8"), 10002);
            String ip = socket.getLocalAddress().getHostAddress();
            ipUser=ip;
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error al obtener la IP", "Error!!.", JOptionPane.ERROR_MESSAGE);
        }
               
        String patron = "\\w+@[a-z]+\\.[a-z]{1,4}";
        Pattern p = Pattern.compile(patron);
        Matcher matcher = p.matcher(campoTextoCorreo.getText());

        if (campoTextoUsuario.getText().isEmpty() || campoTextoCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Es necesario llenar todos los campos", "Error!!.", JOptionPane.ERROR_MESSAGE);
        } else if (!matcher.matches()) {
            JOptionPane.showMessageDialog(rootPane, "Formato incorrecto de email", "Error!!.", JOptionPane.ERROR_MESSAGE);
        } else {
            String nomUsuario = campoTextoUsuario.getText();
            String ipUsuario = ipUser;
            String correoUsuario = campoTextoCorreo.getText();
            
            Usuario u = new Usuario(nomUsuario,correoUsuario,ipUsuario);
            FileOutputStream ficheroSalida = null;
            ObjectOutputStream objetoSalida = null;
            
            try {
                ficheroSalida = new FileOutputStream(rLogin);
                objetoSalida = new ObjectOutputStream(ficheroSalida);
                
            } catch (IOException ex){}
            
            if(objetoSalida != null){
                try{
                objetoSalida.writeObject(u);   
                ficheroSalida.close();
                objetoSalida.close();
                }catch(Exception e){}
            }
            
            
            FrmEmail ventanaPrincipal = new FrmEmail(nomUsuario, ipUsuario, correoUsuario);
            ventanaPrincipal.setVisible(true);
            System.out.println(ipUsuario);
            dispose();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoTextoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoUsuarioKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isLetter(c) && c!=KeyEvent.VK_BACK_SPACE && c!=KeyEvent.VK_SPACE && c!=KeyEvent.VK_PERIOD){
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_campoTextoUsuarioKeyTyped

    private void campoTextoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTextoCorreoKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_campoTextoCorreoKeyTyped

    private void campoTextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoUsuarioActionPerformed
        
        campoTextoCorreo.requestFocus();
        
    }//GEN-LAST:event_campoTextoUsuarioActionPerformed

    private void campoTextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCorreoActionPerformed
        botonAceptarActionPerformed(evt);
    }//GEN-LAST:event_campoTextoCorreoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        FileInputStream ficheroEntrada = null;
        ObjectInputStream objetoEntrada = null;
        
        try {
            ficheroEntrada = new FileInputStream(rLogin);
            objetoEntrada = new ObjectInputStream(ficheroEntrada);
        } catch (IOException ex){}

        if(objetoEntrada != null){
            try{
                login = (Usuario)objetoEntrada.readObject();
            }
            catch(Exception e){}   
        }
        
        if(ficheroEntrada != null && objetoEntrada != null){
            try {
                ficheroEntrada.close();
                objetoEntrada.close(); 
            } catch (IOException ex) {} 
        }

        if(login != null){
            FrmEmail ventanaPrincipal = new FrmEmail(login.getNombre(), login.getIp(), login.getDireccionCorreo());
            ventanaPrincipal.setVisible(true);
            System.out.println(login.getIp());
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoTextoCorreo;
    private javax.swing.JTextField campoTextoUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel metaImagen;
    // End of variables declaration//GEN-END:variables
}
